name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build for iOS Simulator
        run: xcodebuild build -project CasdoorDemo.xcodeproj -scheme CasdoorDemo -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO
